frain-dev/convoy

cmd/main.go, cmd/migrate.go, message.go
This allows us run database migrations. `hookcamp migrate`
=> Add migration command

web/ui/dashboard/package.json, web/ui/dashboard/src/app/models/group.model.ts, web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.html, web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.scss, web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.ts, web/ui/dashboard/src/app/public/login/login.component.ts, web/ui/dashboard/src/app/services/http/http.service.ts, web/ui/dashboard/src/scss/_material-design-reset.scss
- Update UI with group selection
- Add `groupID` query parameters to all requests
=> Update UI with group selection

web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.html, web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.ts
=> Persist filters on dashboard reload

web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.ts
- Add group ID to batch retry
- Clear select items after batch retry
=> 0.3 UI fixes

auth/credential.go, auth/realm_chain/realm_chain.go
=> Prevent (*RealmChain).Authenticate from logging credential password

datastore/event_delivery.go, event_delivery.go, mocks/event_delivery.go, server/event.go
For https://github.com/frain-dev/convoy/issues/236
=> Filter Event Deliveries by multiple status

cmd/version.go, go.mod, net/dispatcher.go, net/dispatcher_test.go
Prefer dynamic version number over hard-coded one
=> Read version number from VERSION file

convoy.json.example
This PR adds a convoy.json.example file
=> adds an example config file

README.md
Fixes the broken link to OpenApi spec in the readme file
=> fix broken link to openapi spec in readme

config/config.go, net/dispatcher.go, net/dispatcher_test.go, worker/task/process_messages.go, worker/task/testdata/Config/basic-convoy-disable-endpoint.json, worker/task/testdata/Config/basic-convoy.json
=> Configure Max response size to store

CONTRIBUTING.md, Makefile
=> Add a contributing.md file

web/ui/dashboard-component/projects/convoy-dashboard/package.json, web/ui/dashboard-component/projects/convoy-dashboard/src/lib/convoy-dashboard.component.ts
fixed auth error on dashboard component
=> fixed auth issue on dashboard-component

cmd/main.go, cmd/queue.go, queue/memqueue/client.go, queue/memqueue/client_test.go, queue/redis/client.go, queue/redis/client_test.go, type.go
- View info about the queue through a CLI tool.
=> Add CLI for Queue Observability

cmd/main.go, cmd/retry.go, datastore/models.go, queue/redis/client.go
=> Add cli retry command to requeue event deliveries

cmd/version.go, net/dispatcher.go, type.go
Add support for embedding the version file during the build process
=> add support for embedding version file

server/ratelimit.go, server/ratelimit_test.go, server/route.go
For https://github.com/frain-dev/convoy/issues/207
=> Group rate limiter and apply to create events

server/event.go, server/event_test.go
Fixes bug with event Delivery Status for Matched Inactive and Active Endpoints
=> fix event delivery status for matched endpoints

net/dispatcher.go, net/dispatcher_test.go, util/crypto.go, util/crypto_test.go, worker/task/process_event_delivery.go
- This pr adds timestamp to headers to allow checks for replay attacks.
=> Add timestamp to header

web/components/app-portal-angular/projects/convoy-app/package.json, web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.ts, web/ui/dashboard/package-lock.json, web/ui/dashboard/package.json, web/ui/dashboard/src/app/private/pages/app/app.component.html, web/ui/dashboard/src/app/private/pages/app/app.component.ts
In this PR, the appId queries were taken out from requests on app portal
Convoy-app v0.0.6 was published
=> App Portal App Id update

web/components/app-portal-angular/projects/convoy-app/package.json, web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.html, web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.scss, web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.ts, web/ui/dashboard/package-lock.json, web/ui/dashboard/package.json, web/ui/dashboard/src/app/private/pages/app/app.component.html, web/ui/dashboard/src/app/private/pages/app/app.component.ts, web/ui/dashboard/src/app/private/private-routing.module.ts
In this pr, the path for app portal was changed, appId was added as a query to getEvents and getEventDeliveries request
=> changed url for app portal

convoy.json.example
=> fix convoy.json.example

README.md
Fix for https://github.com/frain-dev/convoy/issues/609#issue-1206434528
=> Fixed Typo errors and grammar construct error

cmd/main.go, cmd/upgrade.go, datastore/mongo/group.go
```sh
convoy upgrade --from-version v0.4 --to-version v0.5
```
=> feat: add upgrade command to upgrade from convoy v0.4 to v0.5

queue/memqueue/client.go
=> Fix event not created when using an in memory queue

web/ui/dashboard-component/projects/convoy-dashboard/src/lib/convoy-dashboard.component.html, web/ui/dashboard-component/projects/convoy-dashboard/src/lib/convoy-dashboard.component.ts, web/ui/dashboard-component/projects/convoy-dashboard/src/lib/convoy-dashboard.module.ts, web/ui/dashboard-component/projects/convoy-dashboard/src/lib/models/event.model.ts, web/ui/dashboard-component/projects/convoy-dashboard/src/lib/shared-components/time-filter.component.ts
=> Implement time filter

server/event_test.go, services/event_service.go, services/event_service_test.go, worker/task/process_event_creation.go
=> adds support for storing events for disabled apps

datastore/mongo/mongo.go
=> fix index model type

web/ui/dashboard/src/app/models/event.model.ts, web/ui/dashboard/src/app/private/components/create-source/create-source.component.html, web/ui/dashboard/src/app/private/components/create-source/create-source.component.ts, web/ui/dashboard/src/app/private/pages/project/apps/app-details/app-details.component.html, web/ui/dashboard/src/app/private/pages/project/apps/app-details/app-details.component.ts, web/ui/dashboard/src/app/private/pages/project/apps/app-details/create-endpoint/create-endpoint.component.html, web/ui/dashboard/src/app/private/pages/project/apps/app-details/create-endpoint/create-endpoint.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-delivery-details/event-delivery-details.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-delivery-details/event-delivery-details.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-delivery-details/event-delivery-details.service.spec.ts, web/ui/dashboard/src/app/private/pages/project/events/event-delivery-details/event-delivery-details.service.ts, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/events/events.module.ts, web/ui/dashboard/src/scss/_prism.scss
- fix event deliveries in event page
- update text in create source form
- fix event deliveries and deliveries attempt page
=> Fix event deliveries and deliveries attempt page

web/ui/dashboard/src/app/private/components/create-organisation/create-organisation.component.ts, web/ui/dashboard/src/app/private/components/create-source/create-source.component.html, web/ui/dashboard/src/app/private/components/create-source/create-source.component.ts, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/pages/project/sources/sources.component.html, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html, web/ui/dashboard/src/app/private/pages/projects/projects.component.ts, web/ui/dashboard/src/app/private/private.component.html, web/ui/dashboard/src/app/private/private.component.ts, web/ui/dashboard/src/app/private/private.service.ts
delete organisation in localstorage on logout
refresh page on create new organisation to set that organisation
fix create source
=> fix organisation switching

web/ui/dashboard/src/app/components/input/input.component.html, web/ui/dashboard/src/app/components/input/input.component.ts, web/ui/dashboard/src/app/components/tooltip/tooltip.component.html, web/ui/dashboard/src/app/components/tooltip/tooltip.component.spec.ts, web/ui/dashboard/src/app/components/tooltip/tooltip.component.ts, web/ui/dashboard/tailwind.config.js
In this pr, a new tooltip component was created with tail wind and imported into the input component
=> Tooltip component with tailwind

web/ui/dashboard/src/app/private/pages/project/apps/apps.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/sources/sources.component.html, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html
- the correct response while trying to resend/force resend an event is updated
- the arrow icons on the table and pagination buttons were updated
=> fix:  force resend bug

services/event_service.go, services/event_service_test.go
=> add correct validation response for force retry endpoint

datastore/models.go, net/dispatcher.go, net/dispatcher_test.go, pkg/httpheader/httpheader.go, pkg/httpheader/httpheader_test.go, server/ingest.go, server/models/models.go, services/source_service.go, worker/task/process_event_creation.go, worker/task/process_event_delivery.go
Fixes #895 
- Added the `httpheader` package to encapsulate the implementation.
=> Refactored forwarding headers implementation

datastore/models.go, pkg/verifier/verifier.go, server/ingest.go, server/ingest_integration_test.go, web/ui/dashboard/src/app/private/components/create-source/create-source.component.ts
=> feat: allow proxy events without verification

web/ui/dashboard/src/app/app-routing.module.ts, web/ui/dashboard/src/app/components/empty-state/empty-state.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts, web/ui/dashboard/src/app/private/pages/project/apps/apps.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.html, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/sources/sources.component.html, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.ts, web/ui/dashboard/src/app/private/pages/projects/projects.component.html, web/ui/dashboard/src/app/public/app/app.component.html, web/ui/dashboard/src/app/public/app/app.component.ts, web/ui/dashboard/src/app/public/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/services/http/http.service.ts
- prevent app portal from showing login page on 401 error
- support disabling create subscription button on app portal page
- fix create subscription standalone modal UI
=> fix: app portal improvements

web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.html, web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.ts, web/ui/dashboard/src/app/private/components/time-filter/time-filter.component.html, web/ui/dashboard/src/app/private/pages/teams/teams.component.ts
- fixed active states for time filter end date time
- Send correct duration value when creating/editing projects
- fixed cancel invite bug
=> Ui bugfixes

web/ui/dashboard/src/app/app-routing.module.ts, web/ui/dashboard/src/app/components/toggle/toggle.component.html, web/ui/dashboard/src/app/components/toggle/toggle.component.ts, web/ui/dashboard/src/app/private/components/loader/loader.component.html, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/events/events.component.html, web/ui/dashboard/src/app/private/pages/settings/settings.component.html, web/ui/dashboard/src/app/private/pages/settings/settings.component.ts, web/ui/dashboard/src/app/public/login/login.component.html, web/ui/dashboard/src/app/public/signup/signup.component.html, web/ui/dashboard/src/app/public/signup/signup.component.spec.ts, web/ui/dashboard/src/app/public/signup/signup.component.ts, web/ui/dashboard/src/app/public/signup/signup.module.ts, web/ui/dashboard/src/app/public/signup/signup.service.spec.ts, web/ui/dashboard/src/app/public/signup/signup.service.ts, web/ui/dashboard/tailwind.config.js
Frontend implementation for signup page.
=> Signup page

web/ui/dashboard/src/app/private/components/loader/loader.component.html, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/events/events.component.html, web/ui/dashboard/tailwind.config.js
- Fix projects page loader
- Fix events pagination and counter
=> Frontend fixes

worker/task/process_event_delivery.go, worker/task/process_event_delivery_test.go
=> fix endpoint notification email bug

cmd/server.go, cmd/worker.go, datastore/models.go, datastore/object-store/objectstore.go, datastore/object-store/s3.go, server/organisation_invite.go, type.go, worker/task/retention_policies.go
=> Fix retention policy export

.github/workflows/load-test.yml, loadtest/convoy.js, loadtest/setup.sh
=> Add load test scripts

datastore/models.go, datastore/mongo/mongo.go, services/subscription_service.go, web/ui/dashboard/src/app/private/pages/project/sources/sources.component.ts, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html
=> Fix: Subscriptions page error

datastore/models.go, datastore/mongo/mongo.go, services/subscription_service.go, web/ui/dashboard/src/app/private/pages/project/sources/sources.component.ts, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html
* fixed subscription bug
* fixed delete modal bug
* Fix MongoDB indexes (#1027)
* fix: add deleted at to mongodb indexes
* fix: return nil when metadata fields are emtpy
Co-authored-by: Raymond Tukpe <jirevwe@users.noreply.github.com>
=> Fix subscriptions page error (#1026)

datastore/models.go, server/application_integration_test.go, server/models/models.go, services/app_service.go, services/app_service_test.go, web/ui/dashboard/src/app/private/components/create-app/create-app.component.html, web/ui/dashboard/src/app/private/components/create-app/create-app.component.ts, web/ui/dashboard/src/app/private/pages/project/apps/app-details/app-details.component.html, web/ui/dashboard/src/app/private/pages/project/apps/app-details/app-details.component.ts, web/ui/dashboard/src/app/private/pages/project/apps/app-details/create-endpoint/create-endpoint.component.html, web/ui/dashboard/src/app/private/pages/project/apps/app-details/create-endpoint/create-endpoint.component.ts, worker/task/process_event_creation.go
=> adds support for endpoint authentication

web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.html, web/ui/dashboard/src/app/private/pages/project/events/event/event.component.ts, web/ui/dashboard/src/app/public/app/app.component.html, web/ui/dashboard/src/app/public/app/app.component.ts
- remove source filter on app portal
- fix create subscription on app portal
=> App portal fix

web/ui/dashboard/src/app/components/button/button.component.ts, web/ui/dashboard/src/app/components/date-picker/date-picker.component.html, web/ui/dashboard/src/app/components/time-picker/time-picker.component.html, web/ui/dashboard/src/app/private/components/sdk-documentation/sdk-documentation.component.html
Fix broken buttons on
- date picker
- time picker
- sdk component
=> [Fix] Fix broken buttons

web/ui/dashboard/src/app/private/pages/projects/projects.component.html, web/ui/dashboard/src/app/public/login/login.component.ts, web/ui/dashboard/src/app/services/http/http.service.ts
- Redirect user to previous page on login after session timeout
- Fix text on projects page
=> [Feature] Redirect user to previous page on login after session timeout

web/ui/dashboard/src/app/private/private.service.ts
Add page query to sources and subscriptions service method
=> [Fix] Fix pagination on sources and subscriptions

web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.html, web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.ts, web/ui/dashboard/src/app/private/pages/settings/settings.component.ts
=> [Feature] Enable retention policy by default

worker/task/process_event_delivery.go, worker/task/process_event_delivery_test.go
=> fix events in discarded state getting stuck

internal/pkg/migrate/migrate.go, internal/pkg/migrate/migrate_test.go
=> Fix migration tool

server/user.go
- Update 2 minor-typos in `/server/user.go`
=> CONVOY [update] minor typos in backend user-api controller

web/ui/dashboard/src/app/components/select/select.component.html, web/ui/dashboard/src/app/components/select/select.component.ts, web/ui/dashboard/src/app/private/components/create-portal-link/create-portal-link.component.html, web/ui/dashboard/src/app/private/components/create-portal-link/create-portal-link.component.ts, web/ui/dashboard/src/scss/_forms.scss
=> Enhancement: Modify select component to allow search

web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.ts, web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.ts, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts, web/ui/dashboard/src/app/private/pages/project/endpoint-details/endpoint-details.component.html, web/ui/dashboard/src/app/services/http/http.service.ts
In this pr, the following updates were made:
- Toggle prefilled forms on update mode
- Update Endpoint details
- Update refresh token
=> Fix: UI Fixes 

web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts
- Fix toggles for subscription
- Fix values while updating and creating subscriptions
=> Fix subscription

datastore/filter.go, datastore/filter_test.go, internal/pkg/searcher/noop/client.go, internal/pkg/searcher/searcher.go, internal/pkg/searcher/typesense/client.go, internal/pkg/searcher/typesense/client_test.go, mocks/searcher.go, type.go, worker/task/index_document.go, worker/task/index_document_test.go, worker/task/process_event_creation.go
* feat: fix search indexer
* chore: fix tests, discard custom type
* chore: fix filter by tests
* chore: we should only send the actual event details to the index job
=> Fix search indexer (#1448)

web/ui/dashboard/src/app/private/private.service.ts
=> Fix: redirect no org user to get started page

web/ui/dashboard/src/app/components/date-picker/date-picker.component.html, web/ui/dashboard/src/app/components/date-picker/date-picker.component.ts, web/ui/dashboard/src/app/components/table/table.component.ts, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.html, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.html, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts, web/ui/dashboard/src/app/private/pages/project/events/events.component.ts, web/ui/dashboard/src/app/private/pages/project/project.component.html, web/ui/dashboard/src/scss/_forms.scss, web/ui/dashboard/tailwind.config.js
add custom time to  date picker
improve all events tables filters
=> Improve Filter UX

internal/pkg/pubsub/google/client.go
=> fix issue with closing google pub sub client

config/config.go, config/config_test.go
=> Remove the 50kb cap on MaxResponseSize

services/create_endpoint.go
- validate http timeout
- append endpoint uid to portallink
=> Fix http timeout validation

database/postgres/event.go, worker/task/retention_policies.go
=> Ignore events with active deliveries in retention polices

web/ui/dashboard/src/app/private/pages/onboarding/onboarding.component.html, web/ui/dashboard/src/app/private/pages/settings/organisation-settings/organisation-settings.component.html, web/ui/dashboard/src/app/private/pages/settings/settings.module.ts, web/ui/dashboard/src/app/private/private.component.ts, web/ui/dashboard/src/app/private/private.service.ts
In this pr, fixes were made for the following:
- Inability to open the organization modal through the onboarding step
- The project page keeps loading after creating the first organisation even though endpoints have loaded.
=> Fix: Onboarding fix

web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts
=> fix: fix bug with subscription filters

internal/pkg/pubsub/source_loader.go, internal/pkg/pubsub/source_loader_test.go, internal/pkg/pubsub/sqs/client.go
=> fix: fixed message broker bugs

web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.html, web/ui/dashboard/src/styles.scss
=> fix: fix endpoints config buttons

retrystrategies/retry.go
=> Generate backoff progression from IntervalSeconds & RetryLimit

api/models/configuration.go, cmd/hooks/hooks.go, config/config.go, database/postgres/configuration.go, database/postgres/configuration_test.go, database/postgres/postgres_test.go, datastore/models.go, datastore/object-store/objectstore.go, datastore/object-store/s3.go, sql/1698074481.sql, worker/task/retention_policies.go
=> Add Prefix config for S3 storage

database/postgres/event_delivery.go, database/postgres/event_delivery_test.go, datastore/models.go, sql/1698683940.sql, worker/task/process_event_delivery.go
=> Record event delivery latency

api/models/source.go, database/postgres/source.go, datastore/filter.go, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.html, web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts, web/ui/dashboard/src/app/private/private.service.ts
=> Update source and endpoint dropdown with search box

.gitignore, database/postgres/organisation_invite.go
- delete invite after cancellation
- ignore api/dashboard/ui
fixes #1858
=> Delete invite after cancellation

web/ui/dashboard/src/app/private/pages/settings/teams/teams.component.html, web/ui/dashboard/src/app/private/pages/settings/teams/teams.component.ts
=> allow multiple team invites

web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.html, web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.ts, web/ui/dashboard/src/app/private/components/create-source/create-source.component.ts, web/ui/dashboard/src/app/private/pages/project/endpoints/endpoint-secret/endpoint-secret.component.ts
=> Update endpoints form

web/ui/dashboard/src/app/private/components/config-button/config-button.component.html, web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.ts, web/ui/dashboard/src/app/public/app/app.component.html, web/ui/dashboard/src/app/public/app/app.component.ts, web/ui/dashboard/src/app/public/app/app.module.ts
=> Fix endpoint secret modal on portal links

web/ui/dashboard/src/app/components/dropdown-container/dropdown-container.component.ts, web/ui/dashboard/src/app/components/radio/radio.component.html
In this pr:
- the dropdown distortion was fixed
- the radio component was updated for #1934
=> Update radio/dropdown component

web/ui/dashboard/src/app/components/tag/tag.component.ts, web/ui/dashboard/src/app/models/global.model.ts, web/ui/dashboard/src/app/pipes/status-color/status-color.pipe.ts, web/ui/dashboard/src/app/private/pages/project/endpoints/endpoints.component.html, web/ui/dashboard/src/app/private/pages/project/endpoints/endpoints.component.ts, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.html, web/ui/dashboard/src/app/private/pages/project/events/events.component.html, web/ui/dashboard/src/app/private/pages/project/meta-events/meta-events.component.html, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html, web/ui/dashboard/src/app/public/app/app.component.html, web/ui/dashboard/tailwind.config.js
In this pr:
- the endpoint table was updated with id
- Broken doc links were updated
- tag component was modified
=> Update Endpoint table with ID

database/postgres/project.go, datastore/models.go
Prevent a panic from happening when a project config field is nil
=> Fix panic when updating project

web/ui/dashboard/src/app/components/select/select.component.ts, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.html, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.component.ts, web/ui/dashboard/src/app/private/pages/project/subscriptions/subscriptions.module.ts
In this pr:
-  A search bar was added for subscriptions
- The select component bug for multiple selection was fixed
- Events/event delivery interval is cleared appropriately on page exit
=> Add search bar for subscriptions

auth/realm_chain/realm_chain.go, internal/pkg/middleware/middleware.go, services/create_fanout_event.go, services/create_fanout_event_test.go, services/refresh_user_login_token.go, util/endpoint.go
=> Minor fixes

api/handlers/event_delivery.go
Fixed a bug where events from other portal links were also retried from a portal link because the endpoint filter wasn't applied
=> Fixed Portal Link Batch retry bug

web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.html, web/ui/dashboard/src/app/private/components/create-endpoint/create-endpoint.component.ts
=> show endpoint auth config

database/postgres/postgres_collector.go, prometheus/prometheus.yml
- fixed duplicated metrics collection issue
=> metrics fix

database/postgres/delivery_attempts.go, database/postgres/delivery_attempts_test.go, datastore/models.go, worker/task/process_event_delivery.go, worker/task/process_retry_event_delivery.go, worker/task/retention_policies_test.go, worker/task/retry_event_deliveries.go
Fix a bug where some gzipped bytes couldn't be inserted into the db column.
=> Fix Gzip Insert

api/server_suite_test.go, cmd/hooks/hooks.go, cmd/server/server.go, cmd/utils/init_encryption.go, cmd/utils/revert_encryption.go, cmd/utils/rotate_key.go, cmd/worker/worker.go, config/config.go, database/postgres/endpoint.go, database/postgres/portal_link.go, database/postgres/postgres_test.go, database/postgres/subscription.go, internal/pkg/keys/hcpvault.go, internal/pkg/keys/hcpvault_test.go, internal/pkg/keys/keys.go, internal/pkg/keys/local.go, testcon/docker_e2e_integration_test_helper.go, worker/task/retention_policies_test.go
Updates made:
* Use Redis as the main cache
* Removed cache duration timeout
=> updated encryption cache implementation

configs/local/docker-compose.yml, datastore/models.go, internal/pkg/retention/retention.go, net/dispatcher.go, net/dispatcher_test.go, services/create_endpoint.go, services/project_service_test.go, util/endpoint.go, worker/task/process_event_delivery_test.go, worker/task/process_meta_event_test.go, worker/task/process_retry_event_delivery_test.go
=> Allow localhost endpoints

web/ui/dashboard-react/src/app/__root.tsx, web/ui/dashboard-react/src/app/projects/index.tsx, web/ui/dashboard-react/src/components/create-organisation.tsx, web/ui/dashboard-react/src/components/dashboard.tsx, web/ui/dashboard-react/src/contexts/organisation.tsx
This PR extracts the create organisation dialog component to be standalone.
It also enables a user to open the dialog/create another organisation from the top nav.
=> feat: add another organisation

configs/local/convoy.json, web/ui/dashboard-react/src/app/projects_/$projectId/settings.tsx, web/ui/dashboard-react/src/app/projects_/new.tsx, web/ui/dashboard-react/src/components/dashboard.tsx, web/ui/dashboard-react/src/components/ui/sheet.tsx, web/ui/dashboard-react/src/components/ui/table.tsx, web/ui/dashboard-react/src/lib/pipes.ts, web/ui/dashboard-react/src/models/project.model.ts, web/ui/dashboard/src/app/private/components/create-project-component/create-project-component.component.ts, web/ui/dashboard/src/app/services/http/http.service.ts
This PR adds the functionality to
- view a project signature's version history
- set a new signature to the project
=> feat: project signature config

web/ui/dashboard-react/package.json, web/ui/dashboard-react/src/app/projects_/$projectId/settings.tsx, web/ui/dashboard-react/src/components/ui/switch.tsx
This PR adds the feature and (imperfect UI) for updating a project's endpoint configurations.
=> feat: project endpoint config

web/ui/dashboard-react/src/app/projects_/$projectId/settings.tsx, web/ui/dashboard-react/src/models/project.model.ts
Adds functionality for updating the meta events configuration for a project
=> feat: project meta events config

web/ui/dashboard-react/src/app/projects_/$projectId/endpoints/new.tsx, web/ui/dashboard-react/src/components/dashboard.tsx, web/ui/dashboard-react/src/models/endpoint.model.ts, web/ui/dashboard-react/src/routes.gen.ts, web/ui/dashboard-react/src/services/endpoints.service.ts
This PR adds the create endpoint page to the React dashboard
=> feat: create endpoint page

configs/local/convoy.json, web/ui/dashboard-react/src/app/projects_/$projectId/endpoints/$endpointId.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/endpoints/index.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/endpoints/new.tsx, web/ui/dashboard-react/src/routes.gen.ts, web/ui/dashboard-react/src/services/endpoints.service.ts
Adds a form UI and API integration to update an endpoint's details
=> feat: update endpoint

web/ui/dashboard-react/src/app/login.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/sources/index.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/sources/new.tsx, web/ui/dashboard-react/src/app/signup.tsx, web/ui/dashboard-react/src/lib/pipes.ts, web/ui/dashboard-react/src/services/sources.service.ts, web/ui/dashboard-react/tailwind.config.js
This PR adds the
- list sources and the
- delete source
functionalities to the React dashboard
*Pagination for the list not included
=> feat: list sources, delete source

web/ui/dashboard-react/src/app/projects_/$projectId/sources/$sourceId.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/sources/index.tsx, web/ui/dashboard-react/src/app/projects_/$projectId/sources/new.tsx, web/ui/dashboard-react/src/app/projects_/endpoints/$endpointId.tsx, web/ui/dashboard-react/src/app/projects_/endpoints/index.tsx, web/ui/dashboard-react/src/app/projects_/endpoints/new.tsx, web/ui/dashboard-react/src/models/source.ts, web/ui/dashboard-react/src/routes.gen.ts
Update source
- incoming (completed)
- outgoing (done but not tested because cannot create outgoing source for now)
=> feat: update source

api/handlers/auth.go, api/handlers/configuration.go, api/handlers/endpoint.go, api/handlers/organisation.go, api/handlers/portal_link.go, api/handlers/project.go, api/handlers/user.go, api/ingest.go, api/models/configuration.go, auth/realm/jwt/jwt.go, cmd/server/server.go, internal/pkg/middleware/middleware.go, pkg/log/log.go, services/errors.go, services/login_user.go, services/update_user_password.go, util/response.go, web/ui/dashboard/src/app/services/http/http.service.ts
```
change fixes returning of system errors to the client side.
```
=> fix returning of internal errors to client

api/ingest.go
- GitHub and similar providers sign raw request bytes
- Maintains backward compatibility with JSON-converted signatures
- Fixes `"Invalid Signature - Hash does not match"` for form-encoded webhooks
=> fix: verify webhook signatures against raw body first, fallback to JSON
