plugin.go, plugins/add_headers_plugin.go, plugins/add_headers_plugin_test.go
Plugins are going to be at the heart of all operations in Hookcamp. 
Operations will include adding headers programmatically, signing the request et al
=> Add support for plugins

cmd/main.go, config/config.go, config/config_test.go, server/application_test.go, server/dashboard_test.go, server/event_test.go, server/group_test.go, server/middleware_test.go, worker/task/process_event_delivery_test.go
Resolves #282 
This PR adds extra flags to the convoy cli which will override the redis and mongodb DSNs originally set in the config file.
There's a small issue with the way config is being loaded, the `LoadConfig()` function in the config package takes in only s string hence overriding the config values can only be done in after the config is already loaded. My initial thought was to override it on the fly but I don't think that will work. The issue now is that after overriding the config values calling `config.Get()` in a different package will fetch the old values loaded into the atomic store from the convoy.json file and not the overridden value.
=> Add queue and db cli flags

cmd/main.go, config/config.go, config/config_test.go
This PR adds tests to assert that cli flags take preference over config file values and environment variables
=> Add tests for cli flags

datastore/application.go, datastore/application_test.go, datastore/event.go, datastore/event_delivery.go, datastore/group.go, datastore/group_test.go, server/route.go
Badly formed queries were not using indices and thus led to poor performance on a production deployment with high load.
=> Fix queries

cmd/main.go, queue/redis/client.go, queue/storage.go
This PR addresses two things:
1. In `localStorage` we use `Get` and then check if the key exists in the LRU cache. We can use `Contains` to just peek if the key exists. 
2. return errors/nil if there is no error, no need for extra checks.
=> Feat: use contains instead of get / error handling

cmd/server.go, cmd/worker.go, config/config.go, server/route.go, web/ui/website/content/docs/configuration.md
This PR exposes a dedicated health check resource (`/health`) for both the server and worker processes.
Possible issues that might arise could be that the same port is used for both server and worker when running on the same machine or inside the same container. To mitigate this we might need to add another config field to set the worker port, or offset the server port if it's not set.
=> feat: add health check endpoints

cmd/main.go, cmd/version.go, type.go
This allows the version command to run without the `convoy.json` file by introducing a `PersistentPreRun` and `PersistentPostRun` hook on the command itself. 
This also adds a Version field on the root command. So you can run `convoy --version`, which is the same command being run in the version command. 
Resolves #457
=> allow version command to run without config file

server/application.go, server/application_test.go, server/middleware.go, server/route.go
This removes the need for always passing the App ID as a query string to access the routes under app portal.
=> remove app portal app id requirement

server/middleware.go, server/route.go
Removes the need for always passing the groupID as a query string while authenticating with an API Key.
=> removes group id requirement

cmd/main.go, datastore/badger/badger_test.go
This PR removes the default value `"redis"` being set by the queue flag. This caused convoy to still expect a redis DSN even when we set `"in-memory"` in the config file
=> Use queue configuration from convoy.json

util/endpoint.go, util/endpoint_test.go
Application endpoints were being lower-cased before being saved to the database which causes events being delivered to them to return 404 as HTTP URIs are case sensitive according to [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.1).
=> Prevent lowercasing endpoints during cleanup

.github/workflows/immune-test.yml, cmd/server.go, cmd/worker.go, worker/scheduler.go, worker/task/process_event_delivery.go, worker/task/process_event_delivery_test.go
- Sets a span in ProcessEventDelivery using newrelic tracer, so that we can have an estimate of the average time it takes to process an event delivery.
=> Set span in ProcessEventDelivery

convoy.json.example
I was running the convoy example and ran into the following error:
```
Error: invalid character '"' after object key:value pair
```
It looks like there was a comma missing in the example configuration file.
=> Add missing comma to convoy.json.example

README.md
Hello @horlah  👋 
:sunglasses: This is @steveWDamesJr  :sunglasses:
In this fix, I suggest:
Thank you for taking the time to review my PR :pray:
=> Broken Link

cmd/config.go, cmd/main.go, cmd/server.go, config/config.go, config/config_test.go, config/testdata/Config/valid-convoy.json
- Enhanced readability for the entry point of the system. Currently, It’s pretty hard to follow through with how the system is set up from the `cmd` package. The various commands don’t have a consistent way they build `Configuration`. Here’s how the `server` works today;
- `convoy.json` → `environment variables` → `CLI Flags` → `Server CLI Flags` → `Server Defaults`
- Simpler to the above, provide a consistent approach for `subcommands` to add override configuration rather than spin up ad-hoc mechanisms.
1. Build `Configuration` with a more straightforward flow and API.
- Flow
`defaults` → `convoy.json` → `environment variable` → `CLI flags`
- API
```go
// Path to convoy.json
cfgPath := "path/to/convoy.json"
// Load default configuration
err := config.LoadConfig(cfgPath)
// Get …
```
=> Refactored configuration implementation

datastore/models.go, services/event_service.go, services/event_service_test.go, services/group_service_test.go
Fixed force retry bug. It was writing the `EventDelivery` to the wrong queue.
=> Force Retry Bug

cmd/main.go
The server panics because the mongo client in the `postRun` hook doesn't have the same pointer address as the mongo client in the `preRun` hook. This is because the pointer address gets reassigned when `mongo.New` is called. Fixes #902
=> Fix server panic #902

datastore/models.go, datastore/mongo/mongo.go, services/subscription_service.go
This PR adds the `deleted_at` field to all the compound indexes which include the `document status` field. This is because the timestamp is more unique than `Active`/`Deleted` and would prevent duplicate errors to be thrown from the mongodb driver
=> Fix MongoDB indexes

cmd/server.go, cmd/worker.go, worker/consumer.go
* the error return type is unnecessary
refs:
+ https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#NewServeMux
+ https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#NewServer
=> fix (minor): NewConsumer signature

datastore/mongo/event.go, datastore/mongo/event_delivery.go, datastore/mongo/mongo.go, datastore/mongo/subscription.go
For mongodb aggregations, the hack is to `skip`, `sort` and `limit(n)` immediately, then we'd only have to do `lookups` on the remaining `n` records.
=> Fix mongo aggregations

web/ui/dashboard/src/app/private/private.component.html, web/ui/dashboard/src/app/private/private.component.ts
=> Feature: add convoy version to private pages on UI

datastore/filter.go, datastore/filter_test.go, datastore/mongo/mongo.go, internal/pkg/searcher/noop/client.go, internal/pkg/searcher/searcher.go, internal/pkg/searcher/typesense/client.go, internal/pkg/searcher/typesense/client_test.go, internal/pkg/socket/server.go, mocks/searcher.go, type.go, worker/task/index_document.go, worker/task/index_document_test.go, worker/task/process_event_creation.go
There was an issue regarding how the data was being indexed and searched. When we released v0.8 we changed the payload format slightly so the documents were not indexed and when searching we were passing `group_id` instead of `project_id`. We were also incorrectly storing array information in the search backend.
=> Fix search indexer

web/ui/dashboard/src/app/pipes/source-value/source-value.pipe.ts, web/ui/dashboard/src/app/private/components/create-source/create-source.component.ts, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.html, web/ui/dashboard/src/app/private/pages/project/event-logs/event-logs.component.ts, web/ui/dashboard/src/app/private/pages/project/events/event-deliveries/event-deliveries.component.ts
In this pr, an update was made to pause events and event deliveries whenever a search or filtering is initiated, this is to help minimize data conflict whenever a search or filter request is made.
=> fix: pause events polling on search and filtering

cmd/worker/worker.go, worker/task/process_event_delivery.go
Returning `nil` in the `process_event_delivery.go` causes some events to be stuck indefinitely in the `Scheduled` state. This pr fixes this.
=> fix: return proper error instead of nil the process event delivery

services/create_event.go, worker/task/process_dynamic_event_creation.go, worker/task/process_event_creation.go, worker/task/process_event_delivery.go
We're picking the exact same eventdelivery json put on redis this first time the event was queued. This means things like delivery attempts don’t get reflceted if the sending fails the first time for some reason. This PR fixes that
=> Revert to load EventDelivery from DB

cmd/ingest/ingest.go, cmd/server/server.go, cmd/worker/worker.go, config/config.go, docker-compose.dep.yml
This PR includes the following fixes.
- Added the `ingestPort` config to enable the `ingest` cli to use a different separate from the server's port. 
- Added the `logLevel` flag to enable us independently set the `ingest` cli's log level.
- Moved parsing `smtp` cli flags from server to the `worker`.
=> fix: fixed bugs with the ingest & worker cli

configs/local/docker-compose.yml
We are stucking when running the entire docker compose manifest in localhost, we've got the following message:
```shell
➜  local git:(main) docker compose logs postgres redis_server typesense
postgres-1 |chown: /data/postgres: Permission denied
redis_server-1 |chown: /data/postgres: Permission denied
typesense-1 |chown: /data/postgres: Permission denied
```
I propose split up the volumes from each component to volumes session, ex:
```yaml
volumes:
postgres_data:
typesense_data:
redis_data:
```
- https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
=> fix: fixing the permission denied when create a volume in current dir

pkg/compare/compare_test.go, pkg/flatten/flat_test.go
Benchmarks for the flatten and compare packages used for subscription filters
```txt
BenchmarkFlattenArray
BenchmarkFlattenArray-12         	   52860	     22313 ns/op	   16025 B/op	     306 allocs/op
BenchmarkFlattenMap
BenchmarkFlattenMap-12           	   72457	     16310 ns/op	   15968 B/op	     265 allocs/op
BenchmarkFlattenLargeJson
BenchmarkFlattenLargeJson-12     	    1099	   1086014 ns/op	  848443 B/op	    7112 allocs/op
BenchmarkFlattenOperators
BenchmarkFlattenOperators-12     	  216832	      5461 ns/op	    6102 B/op	      84 allocs/op
BenchmarkFlattenWithPrefix
BenchmarkFlattenWithPrefix-12    	  109190	     11172 ns/op	    9858 B/op	     153 allocs/op
BenchmarkCompareNestedArrayOperator
BenchmarkCompareNestedArrayOperator-12    	  131340	      8217 ns/op	    9015 B/op	     103 …
```
=> Add Subcription Filter Benchmarks

.gitignore, pkg/flatten/flat.go, pkg/flatten/flat_test.go
```
change adds support for string request body in the flatten method.
```
=> bg: fix panic when request body is a string

web/ui/dashboard/src/app/private/private.component.html, web/ui/dashboard/src/app/private/private.component.ts
Closes #1967
https://github.com/frain-dev/convoy/assets/25608335/4ac0b1cc-fde3-4d07-9932-f2bb21f1249b
I added a comment in the originating issue about how the logic for forcing users to create an organisation might not be in the best place. https://sourcegraph.com/github.com/frain-dev/convoy/-/blob/web/ui/dashboard/src/app/private/private.component.html?L100
Since the exception for displaying a page when there are no organisations only applies to the `/user-settings` route, then we can get away with it with this band-aid fix.
cc @subomi
=> display user-settings page when there are no orgs

internal/pkg/limiter/pg/client.go, sql/1715118159.sql
This PR aims to reduce the CPU usage of the `convoy.take_token()` function.
=> Update rate limit function

cmd/worker/worker.go, worker/task/process_broadcast_event_creation.go
Create events for the same number of endpoints and not the number of subscriptions
=> Limit number of events created

api/ingest.go, api/ingest_test.go
Closes #2117
This adds support for content type `url-encoded`when ingesting webhooks.
=> feat: Add support for inbound webhooks that use `urlencoded` content type

worker/task/queue_stuck_event_deliveries.go
The intention here should be to initialize a slice with a capacity of len(evs) rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> fix: fix slice init length

api/public_integration_test.go, config/config.go, config/config_test.go, database/postgres/subscription.go, net/dispatcher.go, sql/1733488138.sql
This PR facilitates the creation of new event types created via the API (used by the client libraries) whenever a subscription is created or updated. This ensures that the list of event types available to a customer on the customer portals is up to date.
=> Upsert event types

api/api.go, datastore/models.go, web/ui/dashboard/src/app/models/subscription.ts, web/ui/dashboard/src/app/portal/subscriptions/subscriptions.component.ts
This pull request effectively resolves issues when portal links are run in an iframe.
Within an iframe, the portal link page lacks the essential context a user receives upon logging in.
The following critical issues have been addressed:
- Editing subscriptions no longer generate unauthorized responses, banners, or errors.
- All fields now accurately reflect the licensing status, eliminating the incorrect display of the license lock for licensed instances.
=> fixed portal link UI issues with subscriptions, endpoints and license check

web/ui/dashboard-react/src/app/projects/index.tsx, web/ui/dashboard-react/src/app/projects/route.tsx, web/ui/dashboard-react/src/components/dashboard.tsx, web/ui/dashboard-react/src/contexts/organisation.tsx, web/ui/dashboard-react/src/hooks/use-auth.tsx, web/ui/dashboard-react/src/routes.gen.ts, web/ui/dashboard-react/src/services/http.service.ts, web/ui/dashboard-react/src/services/hubspot.service.ts, web/ui/dashboard-react/src/services/organisations.service.ts
When an organisation is created, other components are not updated.
This PR uses React's Context API (for now) to propagate the update 
- Plans are in order to use a state management library instead of React's Context API because React's Context API is not performant, rendering-wise.
- This PR also changes the way that layout routes are set up, choosing to use the `route.tsx` pattern rather than the `_layout` folder pattern
=> fix: create organisation does not reflect app-wide

web/ui/dashboard-react/src/app/projects/index.tsx, web/ui/dashboard-react/src/app/projects/route.tsx, web/ui/dashboard-react/src/app/projects_/new.tsx, web/ui/dashboard-react/src/app/settings.tsx, web/ui/dashboard-react/src/components/dashboard.tsx, web/ui/dashboard-react/src/services/http.service.ts, web/ui/dashboard-react/src/services/projects.service.ts, web/ui/dashboard-react/src/store/index.ts
The React application has been having inconsistencies in maintaining the states when the current organisation changes or when the project changes.
Modifications in this PR ensures that when an organisation is selected, only projects for that organisation is shown.
It also maintains the organisation state and project state after page reloads and navigation from page to page.
Lastly, it fixes HTML errors that prop up when the dialog component in the /projects/new route appears.
=> fix: inconsistent organisation and project states

web/ui/dashboard-react/src/app/projects_/$projectId/settings.tsx, web/ui/dashboard-react/src/services/http.service.ts, web/ui/dashboard-react/src/services/projects.service.ts
With an imperfect UI, this PR adds the feature for regenerating a project's API key
=> feat: project secrets config

cmd/agent/agent.go, cmd/hooks/hooks.go, cmd/ingest/ingest.go, cmd/main.go, cmd/server/server.go, cmd/stream/stream.go, cmd/worker/worker.go
- The `config` command can now run without connecting to Redis or PostgreSQL
- The `worker` and `ingest` commands have been deprecated.
- Debug logs have been added to give more context to app start-up errors.
=> Entrypoint Enhancements

cmd/agent/agent.go, cmd/stream/stream.go, cmd/worker/worker.go, pkg/compare/compare.go, worker/consumer.go, worker/task/process_broadcast_event_creation.go, worker/task/process_event_creation.go
This pull request brings `main` up to speed with all the changes from `v25.6.x` series, which include:
1. Correctly passing the logger to the workers. 
2. Removing the race condition from the `compare` package.
3. Debug log lines to the broadcast event processing pipeline.
=> feat: cherry pick v25.6.7 fixes
